"""add new column to books

Revision ID: 7255879c3670
Revises: 9d145e8d9373
Create Date: 2023-02-14 10:56:06.579732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7255879c3670'
down_revision = '9d145e8d9373'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('test_something', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'test_something')
    # ### end Alembic commands ###
